# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eec5ec6ad56ca3f7323d51e0697f98bf061ab619936315ad03710a5c855be60ba3e10bdfd58d8fa457cb2e379b9b3d7645269edf06d71af50f6fac4e2b009cbb

test:
  secret_key_base: 2b36f8ddb5515002b84d4c82e365fb7f5c10308d2940b45def0831c081f9d22c3af2d1df58b4599a794bcbe9ec3430c0d79e09c9c4f4b42cf2020b5785a9dd84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
